services:
  notification:
    build: .
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8082"
    depends_on:
      - auth-notification-rabbitmq
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${NOTIFICATION_RABBITMQ_PORT}:5672"
      - "${NOTIFICATION_RABBITMQ_MANAGEMENT_PORT}:15672"
