spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: extract-otp-service

  data:
    redis:
      port: ${TOKEN_REDIS_PORT}
      host: ${TOKEN_REDIS_HOST}

  datasource:
    url: jdbc:postgresql://${TOKEN_DB_HOST}:${TOKEN_DB_PORT}/${TOKEN_DB_NAME}
    username: ${TOKEN_DB_USERNAME}
    password: ${TOKEN_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    pool-size: 2
