spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: extract-otp-service

  data:
    redis:
      port: ${EXTRACT_OTP_REDIS_PORT}
      host: ${EXTRACT_OTP_REDIS_HOST}

  datasource:
    url: jdbc:postgresql://${EXTRACT_OTP_DB_HOST}:${EXTRACT_OTP_DB_PORT}/${EXTRACT_OTP_DB}
    username: ${EXTRACT_OTP_DB_USERNAME}
    password: ${EXTRACT_OTP_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
#    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: ${EXTRACT_OTP_RABBITMQ_HOST}
    port: ${EXTRACT_OTP_RABBITMQ_PORT}
    username: ${EXTRACT_OTP_RABBITMQ_USERNAME}
    password: ${EXTRACT_OTP_RABBITMQ_PASSWORD}

server:
  port: ${EXTRACT_OTP_SERVICE_PORT}

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
  redirect-uri: ${REDIRECT_URI}

jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    pool-size: 2

rabbitmq:
  gmail:
    queue: gmail-queue
