services:
  extract-otp:
    build: .
    ports:
      - "${EXTRACT_OTP_SERVICE_PORT}:8081"
    depends_on:
      - token-db
      - token-redis
      - rabbitmq
    env_file:
      - .env

  setup-gcp:
    build:
      context: ./setup
    container_name: gcp-setup
    environment:
      - PROJECT_ID=otp-extractor-477323
    volumes:
      - ./setup:/setup
    stdin_open: true
    tty: true

  token-redis:
    image: redis:alpine
    container_name: access-token-redis
    ports:
      - "${EXTRACT_OTP_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  token-db:
    image: postgres:alpine
    container_name: token-db
    ports:
      - "${EXTRACT_OTP_DB_PORT}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TOKEN_DB_USERNAME} -d ${TOKEN_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: ${TOKEN_DB_NAME}
      POSTGRES_USER: ${TOKEN_DB_USERNAME}
      POSTGRES_PASSWORD: ${TOKEN_DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: otp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - token-db

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${EXTRACT_OTP_RABBITMQ_PORT}:5672"
      - "${EXTRACT_OTP_RABBITMQ_MANAGEMENT_PORT}:15672"
