services:
  setup-gcp:
    build:
      context: ./setup
    container_name: gcp-setup
    environment:
      - PROJECT_ID=otp-extractor-477323
    volumes:
      - ./setup:/setup
    stdin_open: true
    tty: true

  token-redis:
    image: redis:alpine
    container_name: access-token-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  token-db:
    image: postgres:alpine
    container_name: token-db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${TOKEN_DB_USERNAME} -d ${TOKEN_DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: ${TOKEN_DB_NAME}
      POSTGRES_USER: ${TOKEN_DB_USERNAME}
      POSTGRES_PASSWORD: ${TOKEN_DB_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: otp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - token-db
