services:
  redis:
    container_name: otp-redis
    image: redis:latest
    ports:
      - 6379:6379

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    container_name: otp-postgres-db
    environment:
      POSTGRES_DB: otp-extractor
      POSTGRES_USER: ricky
      POSTGRES_PASSWORD: ricky