version: "3.9"
services:
  authentication:
    container_name: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      auth-redis:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      auth-notification-rabbitmq:
        condition: service_healthy
    env_file:
      - authentication-service/.env
    profiles: [ "authentication", "all" ]

  notification:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8081"
    depends_on:
      auth-notification-rabbitmq:
        condition: service_healthy
    env_file:
      - notification-service/.env
    profiles: [ "notification", "all" ]

  auth-redis:
    container_name: auth-redis
    image: redis:alpine
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [ "authentication", "all" ]

  auth-db:
    container_name: auth-db
    image: postgres:alpine
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: [ "authentication", "all" ]

  auth-notification-rabbitmq:
    container_name: auth-notification-rabbitmq
    image: rabbitmq:4.2.0-management-alpine
    ports:
      - "${NOTIFICATION_RABBITMQ_PORT}:5672"
      - "${NOTIFICATION_RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      NOTIFICATION_RABBITMQ_USERNAME: ${NOTIFICATION_RABBITMQ_USERNAME}
      NOTIFICATION_RABBITMQ_PASSWORD: ${NOTIFICATION_RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: ["authentication", "notification", "all"]
