version: "3.9"
services:
  authentication:
    container_name: authentication-service
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      redis:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - authentication-service/.env
    profiles: [ "authentication", "all" ]

  notification:
    container_name: notification-service
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "${NOTIFICATION_SERVICE_PORT}:8082"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - notification-service/.env
    profiles: [ "notification", "all" ]

  extract-otp:
    container_name: extract-otp-service
    build:
      context: ./extract-otp
      dockerfile: Dockerfile
    ports:
      - "${EXTRACT_OTP_SERVICE}:8081"
    depends_on:
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      extract-otp-db:
        condition: service_healthy
    env_file:
      - extract-otp/.env
    profiles: [ "extract-otp", "all" ]

  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: [ "authentication", "all" ]

  auth-db:
    container_name: auth-db
    image: postgres:alpine
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: [ "authentication", "all" ]

  extract-otp-db:
    container_name: extract-otp-db
    image: postgres:alpine
    ports:
      - "${EXTRACT_OTP_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${EXTRACT_OTP_POSTGRES_DB}
      POSTGRES_USER: ${EXTRACT_OTP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${EXTRACT_OTP_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${EXTRACT_OTP_POSTGRES_USER} -d ${EXTRACT_OTP_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: [ "extract-otp", "all" ]

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.2.0-management-alpine
    ports:
      - "${NOTIFICATION_RABBITMQ_PORT}:5672"
      - "${NOTIFICATION_RABBITMQ_MANAGEMENT_PORT}:15672"
    environment:
      NOTIFICATION_RABBITMQ_USERNAME: ${NOTIFICATION_RABBITMQ_USERNAME}
      NOTIFICATION_RABBITMQ_PASSWORD: ${NOTIFICATION_RABBITMQ_PASSWORD}
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    profiles: ["authentication", "notification", "all"]
