server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: otp-authentication-service

  datasource:
    url: jdbc:postgresql://${AUTH_POSTGRES_HOST}:${AUTH_POSTGRES_PORT}/${AUTH_POSTGRES_DB}
    username: ${AUTH_POSTGRES_USER}
    password: ${AUTH_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${AUTH_JPA_DDL_AUTO}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      host: ${AUTH_REDIS_HOST}
      port: ${AUTH_REDIS_PORT}
  cache:
    type: redis

  rabbitmq:
    host: ${NOTIFICATION_RABBITMQ_HOST}
    port: ${NOTIFICATION_RABBITMQ_PORT}
    username: ${NOTIFICATION_RABBITMQ_USERNAME}
    password: ${NOTIFICATION_RABBITMQ_PASSWORD}

front-end:
  urls:
    - ${AUTH_FRONTEND_URL_1}
    - ${AUTH_FRONTEND_URL_2}
    - ${AUTH_FRONTEND_URL_3}

reset-password:
  queue: ${RESET_PASSWORD_QUEUE}

jwt:
  secret-key: ${AUTH_JWT_SECRET_KEY}
