services:
  authentication:
    build: .
    ports:
      - "${AUTH_SERVICE_PORT}:8080"
    depends_on:
      - auth-db
      - auth-redis
    env_file:
      - .env

  auth-redis:
    container_name: otp-redis
    image: redis:alpine
    ports:
      - "${AUTH_REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-db:
    image: postgres:alpine
    container_name: otp-postgres-db
    environment:
      POSTGRES_DB: ${AUTH_POSTGRES_DB}
      POSTGRES_USER: ${AUTH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${AUTH_POSTGRES_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${AUTH_POSTGRES_USER} -d ${AUTH_POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
      - "${AUTH_POSTGRES_PORT}:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: otp-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - auth-db

  rabbitmq:
    image: rabbitmq:4.2.0-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    ports:
     - "${NOTIFICATION_RABBITMQ_PORT}:5672"
     - "${NOTIFICATION_RABBITMQ_MANAGEMENT_PORT}:15672"
